# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c1aa530ab2ba917bd7755bdfee802c2d80383f06f8104a6a62538ca049979241ef20ef1c252f8e712decfe3f9aa1ac389307ffe2d36d69bdf1251448d0cbaf8

test:
  secret_key_base: 9b62c4d563e8a206d6083d874db380394852ee558956136673e39045257fd81662ae97c8e331fad866955a6751bb4ff73aaa85e99fabbb8d72317ee424a2a7d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
